# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 09:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='commnet_pubdate',
            new_name='comment_pubdate',
        ),
    ]
