# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20171124_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_author',
            field=models.CharField(default='anon', max_length=30),
            preserve_default=False,
        ),
    ]
